name: Dev-Build

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: "src"

      - name: Checkout dev-builds
        uses: actions/checkout@master
        with:
          ref: "dev-builds"
          path: "dev-builds"

      - name: Checkout Aliucord
        uses: actions/checkout@master
        with:
          repository: "Aliucord/Aliucord"
          path: "repo"

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make generateUpdaterJson
          cp **/build/*.zip $GITHUB_WORKSPACE/dev-builds
          cp build/updater.json $GITHUB_WORKSPACE/dev-builds
      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/dev-builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Build $GITHUB_SHA" || exit 0   # do not error if nothing to commit
          git push
